from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
import uuid

class RAGResponse(BaseModel):
    """
    Model representing the response generated by the RAG system
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier for the response")
    query_id: str = Field(..., min_length=1, description="Foreign key to User Query")
    response_text: str = Field(..., min_length=1, description="The answer text generated by the RAG system")
    retrieved_chunks: List[str] = Field(default=[], description="List of chunk IDs used to generate the response")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence score of the response (0-1)")
    created_at: datetime = Field(default_factory=datetime.now, description="Timestamp when response was created")

    class Config:
        json_schema_extra = {
            "example": {
                "id": "123e4567-e89b-12d3-a456-426614174003",
                "query_id": "123e4567-e89b-12d3-a456-426614174002",
                "response_text": "To create a ROS 2 node in Python, you need to import rclpy...",
                "retrieved_chunks": ["chunk_001", "chunk_002", "chunk_003"],
                "confidence_score": 0.92,
                "created_at": "2025-12-15T10:30:05Z"
            }
        }